# Find the Difference

"""
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        indexes = {}
        for i in range(0, len(s)):
            indexes[s[i]] = 1 if s[i] not in indexes else indexes[s[i]] + 1
        for i in range(0, len(t)):
            if t[i] not in indexes:
                return t[i]
            indexes[t[i]] -= 1
            if indexes[t[i]] == -1:
                return t[i]
